/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.User;
import Model.UserList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Asus
 */
public class ManageUserPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageUserPanel
     */
    UserList ul;
    public ManageUserPanel(UserList ul) {
        initComponents();
        this.ul = ul;
        populateTable();
        markFieldsReadOnly();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lastnametxt = new javax.swing.JTextField();
        neuidlb = new javax.swing.JLabel();
        neuidtxt = new javax.swing.JTextField();
        usernamelb = new javax.swing.JLabel();
        firstnamelb = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUserList = new javax.swing.JTable();
        firstnametxt = new javax.swing.JTextField();
        passwordlb = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        emaillb = new javax.swing.JLabel();
        lastnamelb = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        searchtxt = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        viewbtn = new javax.swing.JButton();

        neuidlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        neuidlb.setText("NEUID:");

        usernamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernamelb.setText("User Name:");

        firstnamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstnamelb.setText("First Name:");

        tblUserList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NEU ID", "First Name", "Last Name", "User Name", "Password", "Email ID", "IsEnabled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUserList);

        passwordlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordlb.setText("Password:");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        emaillb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaillb.setText("Email ID:");

        lastnamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastnamelb.setText("Last Name:");

        jLabel1.setText("Search Text:");

        searchtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchtxtActionPerformed(evt);
            }
        });

        searchbtn.setText("Search");
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });

        viewbtn.setText("View");
        viewbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(viewbtn)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchbtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(firstnamelb)
                                            .addComponent(lastnamelb)
                                            .addComponent(neuidlb))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(neuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emaillb)
                                            .addComponent(passwordlb)
                                            .addComponent(usernamelb))
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(183, 183, 183)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn)
                    .addComponent(viewbtn)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuidlb)
                    .addComponent(neuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(firstnamelb)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastnamelb)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelb)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlb)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emaillb)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRowIndex = tblUserList.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblUserList.getModel();
        User u = (User) model.getValueAt(selectedRowIndex, 0);
        ul.deleteUser(u);
        JOptionPane.showMessageDialog(this, "User has been deleted.");
        populateTable();
        
        JOptionPane.showMessageDialog(this, "User has been Deleted");
        resetFields();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblUserList.getModel();
        model.setRowCount(0);
        
        for(User vs : ul.getUserList()){
            Object[] row = new Object[8];
            
            row[0] = vs;
            row[1] = vs.getFirstName();
            row[2] = vs.getLastName();
            row[3] = vs.getUserName();
            row[4] = vs.getPassword();
            row[5] = vs.getEmailID();
            
             model.addRow(row);
        }
    }
    
    private void markFieldsReadOnly(){
        neuidtxt.setEditable(false);
        firstnametxt.setEditable(false);
        lastnametxt.setEditable(false);
        usernametxt.setEditable(false);
        passwordtxt.setEditable(false);
        emailtxt.setEditable(false);
    }
    
    private void resetFields(){
        neuidtxt.setText("");
        firstnametxt.setText("");
        lastnametxt.setText("");
        usernametxt.setText("");
        passwordtxt.setText("");
        emailtxt.setText("");
    }
            
    private void searchtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchtxtActionPerformed

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbtnActionPerformed
        DefaultTableModel ob = (DefaultTableModel) tblUserList.getModel();
        TableRowSorter<DefaultTableModel> tblSorter = new TableRowSorter<>(ob);
        tblUserList.setRowSorter(tblSorter);
        tblSorter.setRowFilter(RowFilter.regexFilter(searchtxt.getText()));
    }//GEN-LAST:event_searchbtnActionPerformed

    private void viewbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbtnActionPerformed
        int selectedRowIndex = tblUserList.getSelectedRow();
        
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a row to delete.");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblUserList.getModel();
        Object vitalSigns = (User) model.getValueAt(selectedRowIndex, 0);
        
        if(vitalSigns instanceof User vs){
            
            neuidtxt.setText(vs.getNeuid());
            firstnametxt.setText(vs.getFirstName());
            lastnametxt.setText(vs.getLastName());
            usernametxt.setText(vs.getUserName());
            passwordtxt.setText(vs.getPassword());
            emailtxt.setText(vs.getEmailID());
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid data in the selected row.");
        }
    }//GEN-LAST:event_viewbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel firstnamelb;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastnamelb;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JLabel neuidlb;
    private javax.swing.JTextField neuidtxt;
    private javax.swing.JLabel passwordlb;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JTable tblUserList;
    private javax.swing.JLabel usernamelb;
    private javax.swing.JTextField usernametxt;
    private javax.swing.JButton viewbtn;
    // End of variables declaration//GEN-END:variables
}
