/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.User;
import Model.UserList;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class UserUpdatePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserUpdatePanel
     */
    User u;
    UserList ul;
    public UserUpdatePanel(User u, UserList ul) {
        initComponents();
        this.u = u;
        this.ul = ul;
        DisplayUserDetails();
        neuidtxt.setEditable(false);
        neuidtxt.setBackground(Color.gray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        neuidtxt = new javax.swing.JTextField();
        lastnametxt = new javax.swing.JTextField();
        firstnametxt = new javax.swing.JTextField();
        usernamelb = new javax.swing.JLabel();
        passwordtxt = new javax.swing.JTextField();
        lastnamelb = new javax.swing.JLabel();
        usernametxt = new javax.swing.JTextField();
        emaillb = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        passwordlb = new javax.swing.JLabel();
        neuidlb = new javax.swing.JLabel();
        firstnamelb = new javax.swing.JLabel();
        updatebtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 73, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Details");

        usernamelb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernamelb.setText("User Name:");

        lastnamelb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastnamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastnamelb.setText("Last Name:");

        emaillb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emaillb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emaillb.setText("Email ID:");

        passwordlb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordlb.setText("Password:");

        neuidlb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        neuidlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        neuidlb.setText("NEU ID:");

        firstnamelb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstnamelb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstnamelb.setText("First Name:");

        updatebtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        updatebtn.setText("Update");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emaillb)
                                    .addComponent(passwordlb)
                                    .addComponent(usernamelb))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnamelb)
                                    .addComponent(neuidlb)
                                    .addComponent(lastnamelb))
                                .addGap(60, 60, 60)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(neuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(166, 166, 166))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {emailtxt, firstnametxt, lastnametxt, neuidtxt, passwordtxt, usernametxt});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neuidlb)
                    .addComponent(neuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstnamelb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnamelb))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamelb)
                    .addComponent(usernametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordlb)
                    .addComponent(passwordtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emaillb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {emailtxt, firstnametxt, lastnametxt, neuidtxt, passwordtxt, usernametxt});

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        String passwordHashed = UserList.HashPassword(passwordtxt.getText());
        User newUser = new User();
        newUser.setNeuid(neuidtxt.getText());
        newUser.setFirstName(firstnametxt.getText());
        newUser.setLastName(lastnametxt.getText());
        newUser.setUserName(usernametxt.getText());
        newUser.setPassword(passwordHashed);
        newUser.setEmailID(emailtxt.getText());
        newUser.setIsEnabled(true);
        newUser.setPreviousPass(new ArrayList<>());
        var isSuccess = ul.updateUser(newUser);
        if(isSuccess){            
            JOptionPane.showMessageDialog(this, "Updated User Details"); 
        }
        else{
            JOptionPane.showMessageDialog(this, "Cannot use any previous passwords! Set new password"); 
        }
    }//GEN-LAST:event_updatebtnActionPerformed
    
    private void DisplayUserDetails(){
        
        neuidtxt.setText(u.getNeuid());
        firstnametxt.setText(u.getFirstName());
        lastnametxt.setText(u.getLastName());
        usernametxt.setText(u.getUserName());
        passwordtxt.setText("");
        emailtxt.setText(u.getEmailID());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emaillb;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel firstnamelb;
    private javax.swing.JTextField firstnametxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lastnamelb;
    private javax.swing.JTextField lastnametxt;
    private javax.swing.JLabel neuidlb;
    private javax.swing.JTextField neuidtxt;
    private javax.swing.JLabel passwordlb;
    private javax.swing.JTextField passwordtxt;
    private javax.swing.JButton updatebtn;
    private javax.swing.JLabel usernamelb;
    private javax.swing.JTextField usernametxt;
    // End of variables declaration//GEN-END:variables
}
